---
# Manage your dotfiles
dotfiles:
  manage: true
  repo: 'https://github.com/surminus/dotfiles.git'
  files:
    ackrc: '~/.ackrc'
    gitconfig: '~/.gitconfig'
    vimrc: '~/.vimrc'
    zshrc: '~/.zshrc'

# Manage homebrew packages
homebrew:
  packages:
    brew:
      - 'jimi'
      - 'hendrix'
    cask:
      - 'eric'
      - 'clapton'
    tap:
      - 'bob'
      - 'marley'

rbenv:
  manage: true
  versions:
    - '1.9.3'
    - '1.9.3-p550'
    - '2.0.0'
    - '2.0.0-p648'
    - '2.2.2'
    - '2.3.0'
    - '2.3.1'
